### PR TITLE
Adding Linux support

### PR DESCRIPTION
**Pull request by JamesHagerman**
This PR pulls together Linux related commits on forks by @devBrouwer and @gbin and updates everything to work with the current master.

I improved the new `linux/Makefile` so the flags are in the correct order.

I also ignored some warnings caused by the `LOOKUP_ENTRY` Macro in `keycode.cpp` as I couldn't figure out a simpler way to actually make the warning go away without rewriting some code.

Annnd I updated the `readme.md` to do a little better job at explaining how to compile under Linux.

Please accept this PR!

### CODE REVIEW

**Comment by wilba** [comment]
Thanks... I'll pull this into the new release this weekend!

**Comment by wilba** [comment]
I'm still looking at the changes.

The thing about using "usage page" being Windows specific is new to me... using "interface number" means that QMK must compile with the Raw HID interface at a constant interface number, but that might not happen if compiled with MOUSE_ENABLE on, or EXTRAKEY_ENABLE off, etc.

So I will move the Raw HID interface up in the list so it's at a constant number of 1.

**Comment by wilba** [comment]
I've pulled this in, but it still needs some tweaks.

**Comment by wilba** [comment]
Stupid github won't let me message you directly lol...

Code is now up-to-date with the now constant interface number of 1 in QMK master ;-)

Now all platforms will use interface number instead of usage/usage page.

Thanks for your help!

**Comment by devBrouwer** [comment]
Happy to have been of help :) @Wilba6582 Thanks for merging this. And @JamesHagerman thanks for updating and improving this!

**Comment by JamesHagerman** [comment]
@Wilba6582 Thank you for updating the code and accepting this PR!

@devBrouwer Thank you for your initial work!

**Pull request merged**
